# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('msg_title', models.CharField(max_length=200)),
                ('msg', models.CharField(max_length=2000)),
                ('msg_author', models.CharField(max_length=50)),
            ],
        ),
    ]
